### PR TITLE
Using docker container from quay.io

### PR DESCRIPTION
**Pull request by kiwiroy**
Using the prebuilt container seems like a good idea in terms of efficiency and simplicity of the yaml definition. Are there any drawbacks?

### CODE REVIEW

**Comment by vsoch** [comment]
Have you tested this? Typically a container with Singularity has permissions or other issues because we aren’t running it privileged, hence the strategy here to install natively.

**Comment by kiwiroy** [comment]
> Have you tested this? 

yes, but only with simple command line applications, including this one now.

```shell
$ export GITHUB_TOKEN=...
$ curl -L -H "Authorization: token $GITHUB_TOKEN" \
    https://api.github.com/repos/kiwiroy/github-ci/actions/artifacts/18516234/zip > container.zip
$ unzip container.zip
$ singularity run container.sif 
Hold me closer... tiny container :D
```

**Comment by vsoch** [comment]
I like this approach, and I have a proposal for you - I do think this approach would work for simple builds, but there is likely to be some issue depending on the build. What do you think about creating a separate workflow - called .github/workflows/container.yml (or something intuitive like that) and then providing this option? Then in the README, clearly state that go.yml is intended to show a native install, and container.yml uses a pre-built container on quay.io. Then the user can select whichever recipe is best fit for their use case.

**Comment by kiwiroy** [comment]
Sounds good.

- [ ] Augment this PR create new file rather than edit.
- [ ] Rename original `go.yml` to `native.yml` for clarity?
- [ ] Update README

**Comment by vsoch** [comment]
+1 to make the go.yaml more clearly named! I would even go further and call it `native-install.yml`.

**Review by vsoch — APPROVED** [review]
Beautiful! Are you finished up @kiwiroy and this is ready for merge?

**Comment by kiwiroy** [comment]
Thanks. I'd consider it ready for merging.

**Comment by vsoch** [comment]
Thank you @kiwiroy ! I think this greatly improves the repository with the additional example.

**Pull request merged**
